### ISSUE TITLE
Utilizar menús html desplegables en lugar de recargar las páginas completas.

### ISSUE THREAD

**Issue by rafaelleru** [acanas/swad-core#13]
Por ejemplo en la página de archivos cuando quieres abrir una carpeta la página se recarga completa en lugar de simplemente expandirse.

**Comment by acanas** [comment]
Fixed in version swad-core 17.17.2 (2017-10-04) .
Now the folder expansion / contraction is done in JavaScript on the client, without reloading any information from the server, which is a gain in terms of usability and speed.
