### ISSUE TITLE
Stack overwrite in swad_group.c

### ISSUE THREAD

**Issue by raistmaj** [acanas/swad-core#2]
The function bool Grp_CheckIfGroupBelongsToCourse (long, long) contains an array of char of size 128, the minimum size of the query is 141 (if both longs are replaced by 0), this will produce an stack overwrite. 

As the size of parameters is probably limited in the input I doubt a possible shell injection or any method to gain access to the underlying system, just a DoS.

**Comment by acanas** [comment]
Thank you! The bug has been fixed in version 15.192.12
