### ISSUE TITLE
make fails due to missing swad_cookie.[c,h] files from repository

### ISSUE THREAD

**Issue by naderra** [acanas/swad-core#20]
`$ git clone https://github.com/acanas/swad-core.git`
`$ cd swad-core`
`$  make`
`gcc -Wall -Wextra -mtune=native -Os -s   -c -o swad_action.o swad_action.c`
`swad_action.c:40:10: fatal error: swad_cookie.h: No such file or directory`
` #include "swad_cookie.h"`
`          ^~~~~~~~~~~~~~~`
`compilation terminated.`
`<builtin>: recipe for target 'swad_action.o' failed`
`make: *** [swad_action.o] Error 1`

Both swad_cookie.h and swad_cookie.c appear to be missing from the github repo.

**Comment by acanas** [comment]
Both files were added. Thank you very much for notifying the issue.
