### ISSUE TITLE
make fails due to missing swad_building.[c,h] files from repository

### ISSUE THREAD

**Issue by Jayce816** [acanas/swad-core#24]
$ make
gcc -Wall -Wextra -mtune=native -O2 -s   -c -o swad_account.o swad_account.c
In file included from swad_group.h:31:0,
                 from swad_file_browser.h:33,
                 from swad_assignment.h:31,
                 from swad_global.h:37,
                 from swad_account.c:42:
swad_room.h:30:10: fatal error: swad_building.h: No such file or directory
 #include "swad_building.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'swad_account.o' failed
make: *** [swad_account.o] Error 1

**Comment by acanas** [comment]
Added those two files. Thank you!
