### ISSUE TITLE
Unable to run sql script for installation

### ISSUE THREAD

**Issue by proxa** [acanas/swad-core#9]
I have run into an error while running the swad.sql script

`[alureon.anna] ~/code/c/swad-core/sql $ mysql -u swad -p < swad.sql`
`Enter password:`
`ERROR 1071 (42000) at line 700: Specified key was too long; max key length is 1000 bytes`

I did some digging but I'm not sure why this error is happening.

**Comment by proxa** [comment]
At first I figured it was a MySQL version problem, but I am also building on CentOS 6 - like the installation guide.  I obtained MySQL though yum.

**Comment by acanas** [comment]
Thank you very much for reporting the error. This was an erroneously defined field in the swad.sql file. Instead of VARCHAR (2047) the correct thing is VARCHAR (255). I have corrected it in version 16.166.

**Comment by proxa** [comment]
Can confirm fix works
